# Generated by Django 5.1.5 on 2025-03-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='encryption_key',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
