# Generated by Django 5.1.5 on 2025-03-25 10:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_customuser_encryption_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_follows',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
