# Generated by Django 5.1.5 on 2025-03-25 10:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_customuser_user_follows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_follows',
            field=models.ManyToManyField(blank=True, related_name='follows', to=settings.AUTH_USER_MODEL),
        ),
    ]
