steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/graphconnect/graphconnect-repo:$SHORT_SHA'
      - '--build-arg'
      - 'DATABASE_NAME=postgres'
      - '--build-arg'
      - 'DATABASE_USER=postgres'
      - '--build-arg'
      - 'DATABASE_PASSWORD=jasonlndmsocialapp'
      - '--build-arg'
      - 'DATABASE_HOST=34.79.74.37'
      - '--build-arg'
      - 'DATABASE_PORT=5432'
      - '.'

images:
  - 'gcr.io/graphconnect/graphconnect-repo:$SHORT_SHA'
