version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: graphconnect
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: jasonlndmsocialapp2025*
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build:
      context: .
    container_name: django-backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ./uploaded_images:/app/uploaded_images
    environment:
      - DATABASE_NAME=graphconnect
      - DATABASE_HOST=db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=jasonlndmsocialapp2025*
      - DATABASE_PORT=5432
      - DJANGO_SETTINGS_MODULE=GraphConnectSettings.settings
      - PYTHONUNBUFFERED=1
      - PORT=8080

  frontend:
    build:
      context: ./frontend
    container_name: vue-frontend
    ports:
      - "8081:8080"
    depends_on:
      - backend

volumes:
  pgdata:
