# Generated by Django 5.1.5 on 2025-01-30 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreatePosts', '0002_remove_comment_related_post_comment_related_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='related_post',
        ),
        migrations.AddField(
            model_name='comment',
            name='related_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CreatePosts.post'),
        ),
    ]
