# Generated by Django 5.1.5 on 2025-01-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreatePosts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='related_post',
        ),
        migrations.AddField(
            model_name='comment',
            name='related_post',
            field=models.ManyToManyField(related_name='comment_post', to='CreatePosts.post'),
        ),
    ]
