# Generated by Django 5.1.5 on 2025-01-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreatePosts', '0003_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_post',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
