# Generated by Django 5.1.5 on 2025-02-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreatePosts', '0005_remove_post_comments_comment_related_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image_comment',
            field=models.ImageField(blank=True, upload_to='uploaded_images/'),
        ),
    ]
