# Generated by Django 5.1.7 on 2025-06-05 17:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreatePosts', '0008_post_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image_comment',
            field=models.ImageField(blank=True, upload_to='comments/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_post',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='labels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), default=list, size=None),
        ),
    ]
