# Generated by Django 5.1.7 on 2025-06-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreatePosts', '0011_alter_post_image_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='image_post',
        ),
        migrations.AddField(
            model_name='comment',
            name='image_comment',
            field=models.ImageField(blank=True, null=True, upload_to='uploaded_images/'),
        ),
    ]
