# Generated by Django 5.1.7 on 2025-07-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreatePosts', '0012_remove_comment_image_post_comment_image_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image_comment',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_post',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
