# Generated by Django 5.1.5 on 2025-01-29 10:50

import CreatePosts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreatePosts', '0014_alter_post_image_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_post',
            field=models.FileField(upload_to=CreatePosts.models.user_directory_path),
        ),
    ]
