# Generated by Django 5.1.5 on 2025-01-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreatePosts', '0016_alter_post_image_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_post',
            field=models.FileField(upload_to='uploaded_images/'),
        ),
    ]
