# Generated by Django 5.1.5 on 2025-01-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreatePosts', '0018_alter_post_image_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_post',
            field=models.ImageField(blank=True, upload_to='uploaded_images/'),
        ),
    ]
