# Generated by Django 5.1.5 on 2025-02-06 17:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_system', '0002_message_user_message_delete_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_message',
            name='sender',
        ),
        migrations.AddField(
            model_name='user_message',
            name='user_followss',
            field=models.ManyToManyField(blank=True, related_name='followss', to=settings.AUTH_USER_MODEL),
        ),
    ]
