# Generated by Django 5.1.5 on 2025-02-07 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_system', '0002_alter_message_message_recipient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message_recipient',
        ),
    ]
