# Generated by Django 5.1.5 on 2025-02-06 17:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_system', '0003_remove_user_message_sender_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_message',
            name='user_followss',
        ),
        migrations.AddField(
            model_name='user_message',
            name='sending_from_to',
            field=models.ManyToManyField(blank=True, related_name='from_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
