# Generated by Django 5.1.5 on 2025-02-06 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_system', '0004_remove_user_message_user_followss_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_message',
            name='related_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chat_system.message'),
        ),
    ]
