# Generated by Django 5.1.5 on 2025-03-24 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_system', '0005_alter_message_message_recipient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='content_hash',
        ),
    ]
