# Generated by Django 5.1.5 on 2025-03-25 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_system', '0008_remove_message_content_hash_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='encrypted_content',
        ),
    ]
