# Generated by Django 5.1.5 on 2025-03-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_system', '0011_alter_message_message_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='recipient_encryption_key',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_encryption_key',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
