# Generated by Django 5.1.5 on 2025-03-25 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_system', '0012_message_recipient_encryption_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='recipient_encryption_key',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender_encryption_key',
        ),
    ]
