# Generated by Django 5.1.5 on 2025-03-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_system', '0013_remove_message_recipient_encryption_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='encryption_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
