# Generated by Django 5.1.5 on 2025-03-25 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_system', '0009_rename_content_message_encrypted_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='encrypted_content',
            new_name='content',
        ),
    ]
